import { spawn } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { composeChatPrompt, withWorkspaceBoundary } from "./cursor.js";
import { parseArtifactHints } from "./parse.js";
import type {
  AgentDriver,
  AgentEvent,
  ChatInput,
  RunInput,
  RunResult,
} from "./types.js";
import { normalizeWorkspaceRoot } from "./workspacePath.js";

export const DSH_DEFAULT_MODEL = "deepseek-v4-flash";
const DSH_DEFAULT_BIN = "dsh";
const DSH_DEFAULT_TIMEOUT_MS = 30 * 60 * 1000;
const KILL_GRACE_MS = 3000;

export type DshDriverOptions = {
  /** dsh executable; defaults to "dsh" resolved from PATH. */
  dshBin?: string;
  /** Model id passed via an agent-default-model patch overlay. */
  modelId?: string;
  /** Injected into the child env as DEEPSEEK_API_KEY. */
  apiKey?: string;
  /** Injected into the child env as DEEPSEEK_BASE_URL. */
  baseURL?: string;
  /** Run timeout; 0 disables. Defaults to 30 minutes. */
  timeoutMs?: number;
};

export type DshRunResult = {
  code: number | null;
  signal: string | null;
  stdout: string;
  stderr: string;
};

/**
 * Run `dsh --profile headless "<prompt>"` in the workspace directory and
 * return its stdout. Cursor-compatible drivers stream; headless prints the
 * final assistant message once, so callers get the whole text at completion.
 */
async function runHeadless(
  opts: DshDriverOptions,
  prompt: string,
  workspacePath: string,
  patchFile: string | null,
): Promise<DshRunResult> {
  const cwd = normalizeWorkspaceRoot(workspacePath);
  const args = ["--profile", "headless"];
  if (patchFile) args.push("--patch", patchFile);
  args.push(withWorkspaceBoundary(prompt, cwd));

  const child = spawn(opts.dshBin ?? DSH_DEFAULT_BIN, args, {
    cwd,
    env: {
      ...process.env,
      ...(opts.apiKey ? { DEEPSEEK_API_KEY: opts.apiKey } : {}),
      ...(opts.baseURL ? { DEEPSEEK_BASE_URL: opts.baseURL } : {}),
    },
    stdio: ["ignore", "pipe", "pipe"],
  });

  const stdout: string[] = [];
  const stderr: string[] = [];
  child.stdout?.on("data", (d: Buffer) => stdout.push(d.toString()));
  child.stderr?.on("data", (d: Buffer) => stderr.push(d.toString()));

  const timeoutMs = opts.timeoutMs ?? DSH_DEFAULT_TIMEOUT_MS;
  let timer: ReturnType<typeof setTimeout> | undefined;
  const timedOut = new Promise<true>((resolve) => {
    if (timeoutMs > 0) {
      timer = setTimeout(() => {
        child.kill("SIGTERM");
        setTimeout(() => child.kill("SIGKILL"), KILL_GRACE_MS).unref();
        resolve(true);
      }, timeoutMs);
    }
  });

  const exit = new Promise<{ code: number | null; signal: string | null }>(
    (resolve, reject) => {
      child.once("exit", (code, signal) => resolve({ code, signal }));
      child.once("error", reject);
    },
  );

  let didTimeout = false;
  try {
    const winner = await Promise.race([
      exit.then((r) => ({ exit: r, timeout: false as const })),
      timedOut.then(() => ({ exit: null, timeout: true as const })),
    ]);
    didTimeout = winner.timeout;
  } finally {
    if (timer) clearTimeout(timer);
  }

  // Give stdio pipes a tick to flush after exit.
  await new Promise((r) => setImmediate(r));

  if (didTimeout) {
    return {
      code: null,
      signal: "SIGTERM",
      stdout: "",
      stderr: `dsh timed out after ${timeoutMs}ms`,
    };
  }
  return {
    ...(await exit),
    stdout: stdout.join(""),
    stderr: stderr.join(""),
  };
}

/**
 * Write a one-time agent-default-model patch overlay; null = use dsh default.
 *
 * modelId accepts either a plain model id (provider defaults to
 * deepseek-official, whose ids pass through to the DeepSeek API unchanged)
 * or "provider/model" to select another mounted provider route, e.g.
 * "openai/gpt-5" or "anthropic/claude-sonnet-4-5" (pi-ai adapter routes).
 */
function buildModelPatch(opts: DshDriverOptions): string | null {
  const raw = opts.modelId?.trim();
  if (!raw || raw === DSH_DEFAULT_MODEL) return null;
  let provider = "deepseek-official";
  let model = raw;
  const slash = raw.indexOf("/");
  if (slash > 0 && slash < raw.length - 1) {
    provider = raw.slice(0, slash).trim();
    model = raw.slice(slash + 1).trim();
  }
  const dir = mkdtempSync(path.join(tmpdir(), "aiw-dsh-patch-"));
  const file = path.join(dir, "model.yml");
  writeFileSync(
    file,
    [
      "# Generated by ai-workforce DshDriver: override the default model.",
      "- id: agent-default-model",
      "  config:",
      `    provider: ${provider}`,
      `    model: ${model}`,
      "",
    ].join("\n"),
    "utf8",
  );
  return file;
}

export class DshDriver implements AgentDriver {
  readonly id = "dsh";
  readonly displayName = "DeepSeek Harness";

  private readonly patchFile: string | null;

  constructor(private readonly opts: DshDriverOptions = {}) {
    this.patchFile = buildModelPatch(opts);
  }

  async oneshot(input: RunInput): Promise<RunResult> {
    input.onProgress?.("执行中：启动 DeepSeek Harness…");
    try {
      const r = await runHeadless(
        this.opts,
        input.prompt,
        input.workspacePath,
        this.patchFile,
      );
      if (r.code !== 0) {
        const detail = (r.stderr || r.stdout || "").trim();
        return {
          status: "error",
          summary: `dsh exited with code ${r.code}${detail ? `: ${detail.slice(0, 500)}` : ""}`,
          artifacts: [],
        };
      }
      const summary = r.stdout.trim();
      if (!summary) {
        return {
          status: "error",
          summary: "DeepSeek Harness returned empty output",
          artifacts: [],
        };
      }
      input.onProgress?.("执行中：DSH 完成，解析结果…");
      return {
        status: "ok",
        summary,
        artifacts: parseArtifactHints(summary),
      };
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      return { status: "error", summary: message, artifacts: [] };
    }
  }

  async *chatStream(input: ChatInput): AsyncIterable<AgentEvent> {
    if (input.signal?.aborted) {
      yield { type: "done", summary: "*(已打断)*" };
      return;
    }

    // headless has no incremental stdout; run once, emit the full text.
    const cwd = normalizeWorkspaceRoot(input.workspacePath);
    const prompt = composeChatPrompt({ ...input, workspacePath: cwd });
    const args = ["--profile", "headless"];
    if (this.patchFile) args.push("--patch", this.patchFile);
    args.push(prompt);

    const child = spawn(this.opts.dshBin ?? DSH_DEFAULT_BIN, args, {
      cwd,
      env: {
        ...process.env,
        ...(this.opts.apiKey ? { DEEPSEEK_API_KEY: this.opts.apiKey } : {}),
        ...(this.opts.baseURL ? { DEEPSEEK_BASE_URL: this.opts.baseURL } : {}),
      },
      stdio: ["ignore", "pipe", "pipe"],
    });

    const stdout: string[] = [];
    const stderr: string[] = [];
    child.stdout?.on("data", (d: Buffer) => stdout.push(d.toString()));
    child.stderr?.on("data", (d: Buffer) => stderr.push(d.toString()));

    let interrupted = false;
    const onAbort = () => {
      interrupted = true;
      child.kill("SIGTERM");
    };
    input.signal?.addEventListener("abort", onAbort);

    const timeoutMs = this.opts.timeoutMs ?? DSH_DEFAULT_TIMEOUT_MS;
    const timer =
      timeoutMs > 0
        ? setTimeout(() => {
            interrupted = true;
            child.kill("SIGTERM");
            setTimeout(() => child.kill("SIGKILL"), KILL_GRACE_MS).unref();
          }, timeoutMs)
        : undefined;

    try {
      const exit = await new Promise<{ code: number | null; signal: string | null }>(
        (resolve, reject) => {
          child.once("exit", (code, signal) => resolve({ code, signal }));
          child.once("error", reject);
        },
      );
      await new Promise((r) => setImmediate(r));

      if (input.signal?.aborted || interrupted) {
        yield { type: "done", summary: "*(已打断)*" };
        return;
      }
      if (exit.code !== 0) {
        const detail = (stderr.join("") || stdout.join("")).trim();
        yield {
          type: "error",
          message: `dsh exited with code ${exit.code}${detail ? `: ${detail.slice(0, 500)}` : ""}`,
        };
        return;
      }
      const text = stdout.join("").trim();
      if (!text) {
        yield { type: "error", message: "DeepSeek Harness returned empty output" };
        return;
      }
      yield { type: "text_delta", text };
      yield { type: "done", summary: text };
    } catch (e) {
      if (input.signal?.aborted) {
        yield { type: "done", summary: "*(已打断)*" };
        return;
      }
      const message = e instanceof Error ? e.message : String(e);
      yield { type: "error", message };
    } finally {
      input.signal?.removeEventListener("abort", onAbort);
      if (timer) clearTimeout(timer);
      if (child.exitCode === null && child.signalCode === null) child.kill("SIGKILL");
    }
  }
}
